### ISSUE TITLE
crowdin translate

### ISSUE THREAD

**Issue by xleb-normal** [Inconn/fix-antighost-fork-crash#1]
the mod requires crowdin translate, although it is not written anywhere about it, and it is also unclear where to get this mod

**Comment by Inconn** [comment]
This was an internal library that was embedded into the AntiGhost mod, and it was the mod that was crashing the game. I think that this fix was added into AntiGhost FORK though, so I don't think it's required anymore. And if it's causing issues then I would just remove it.

**Comment by Inconn** [comment]
https://github.com/gbl/CrowdinTranslate
